version: "3.8"

services:
  client:
    image: pf-client
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    container_name:
      pf-client
