version: '3.8'

services:
  programming-forum-prod:
    image: pf-client-prod
    environment:
      - SECRET=helloworld
      - MONGODB_URI=mongodb://the_username:the_password@pf-mongo-prod/the_database
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    container_name: programming-forum-prod

  mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./server/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    container_name: pf-mongo-prod

volumes:
  mongo_data: