version: '3.8'

services:
  client:
    image: pf-client-prod
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: pf-client-prod

  mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./server/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    container_name: pf-mongo-prod

  server:
    image: pf-server-prod
    depends_on:
      - "mongo"
      - "client"
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - SECRET=helloworld
      - MONGODB_URI=mongodb://the_username:the_password@pf-mongo-prod/the_database
    ports:
      - 4000:4000
    container_name: pf-server-prod

volumes:
  mongo_data: