version: '3.8'

services:
  programmingforum-mongo-prod:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./server/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    container_name: programmingforum-mongo-prod

  programming-forum-prod:
    environment:
      - NODE_ENV=production
      - SECRET=helloworld
      - MONGODB_URI=mongodb://the_username:the_password@programmingforum-mongo-prod/the_database
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    container_name: programming-forum-prod
    depends_on:
      - programmingforum-mongo-prod

volumes:
  mongo_data: