version: '3.8'

services:
  pf-mongo-test:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./server/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    container_name: pf-mongo-test

  programming-forum-test:
    environment:
      - NODE_ENV=test
      - SECRET=helloworld
      - TEST_MONGODB_URI=mongodb://the_username:the_password@pf-mongo-test/the_database
    build:
      context: ./
      dockerfile: test.Dockerfile
    ports:
      - 4000:4000
    container_name: programming-forum-test
    depends_on:
      - pf-mongo-test

volumes:
  mongo_data: