version: '3.8'

services:
  mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    restart: always
    volumes: 
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    container_name: pf-mongo


  server:
    image: pf-server
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      - SECRET=helloworld
      - MONGODB_URI=mongodb://the_username:the_password@pf-mongo/the_database
    ports:
      - 4000:4000
    volumes:
      - ./:/usr/src/app
    container_name: pf-server

  debug-helper:
    image: busybox