name: Heroku Deploy

on:
  push:
    branches:
      - main

jobs:
  heroku_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "tsoha-2021-tl"
          heroku_email: ${{ secrets.EMAIL }}
          healthcheck: "https://tsoha-2021-tl.herokuapp.com/api/testing/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true