name: Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches: [main]
    types: [opened]

jobs:
  test_and_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: npm install
        run: npm install && cd react-ui && npm install
      - name: lint
        run: npm run eslint
      - name: e2e tests
        uses: cypress-io/github-action@v2
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET: 'supersecretkey'
        with:
          browser: chrome
          headless: true
          start: npm run start:full
          wait-on: http://localhost:3000

      - name: run if branch is main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "MAIN123"

      - name: run if branch is development
        if: ${{ github.ref == 'refs/heads/development' }}
        run: echo "DEV123"
